language: php

php:
  - 7

before_install:
  - git clone https://github.com/nikic/php-ast.git build/ast
  - cd ./build/ast/
  - phpize
  - ./configure
  - make
  - sudo make install
  - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ./../../
  - travis_retry composer self-update

install:
  - composer --prefer-source install

script:
  - mkdir -p build
  - phpunit --colors -c phpunit.xml
