language: php

php:
  - 7
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"

cache:
  directories:
    - ./vendor

before_install:
  - mkdir build
  - git clone --depth 1 https://github.com/nikic/php-ast.git build/ast
  - cd ./build/ast/
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ./../../
  - travis_retry composer self-update

install:
  - composer --prefer-source install

script:
  - ./vendor/bin/phpunit --colors -c phpunit.xml
  - php package.php

before_deploy:
  - php package.php

deploy:
  provider: releases
  api_key: $API_KEY
  file: build/phan.phar
  skip_cleanup: true
  on:
    tags: true
